import { act, renderHook } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import type { ReactNode } from 'react';
import { expect, it, vi } from 'vitest';
import { useAssistantThread } from '@/hooks/useAssistant';
const get = vi.fn();
vi.mock('@/lib/api', () => ({ api: { get: (...args: unknown[]) => get(...args) } }));
vi.mock('@/context/AuthContext', () => ({ useAuthScopeKey: () => 'scope' }));
const conversation = { id: 1, title: 'History', createdAt: '', updatedAt: '' };
const message = (id: number, role = 'user') => ({ id, conversationId: 1, role, content: String(id), createdAt: '' });
it('loads recent detail first and explicitly prepends older visible messages', async () => {
  get.mockResolvedValueOnce({ conversation, messages: [message(3), message(4, 'assistant')], nextCursor: 'older' });
  const qc = new QueryClient();
  const wrapper = ({ children }: { children: ReactNode }) => <QueryClientProvider client={qc}>{children}</QueryClientProvider>;
  const hook = renderHook(() => useAssistantThread({ enabled: false }), { wrapper });
  await act(async () => { await hook.result.current.loadConversation(1); });
  expect(hook.result.current.hasOlderMessages).toBe(true);
  expect(hook.result.current.messages.map((row) => row.id)).toEqual([3, 4]);
  get.mockResolvedValueOnce({ conversation, messages: [message(1), message(2, 'tool'), message(3)], nextCursor: null });
  await act(async () => { await hook.result.current.loadOlderMessages(); });
  expect(get).toHaveBeenLastCalledWith('/assistant/conversations/1?cursor=older');
  expect(hook.result.current.messages.map((row) => row.id)).toEqual([1, 3, 4]);
  expect(hook.result.current.hasOlderMessages).toBe(false);
  act(() => hook.result.current.newChat());
  expect(hook.result.current.messages).toEqual([]);
  qc.clear();
});
it('ignores an older page that arrives after starting another chat', async () => {
  const qc = new QueryClient();
  const wrapper = ({ children }: { children: ReactNode }) => <QueryClientProvider client={qc}>{children}</QueryClientProvider>;
  get.mockResolvedValueOnce({ conversation, messages: [message(3)], nextCursor: 'older' });
  const hook = renderHook(() => useAssistantThread({ enabled: false }), { wrapper });
  await act(async () => { await hook.result.current.loadConversation(1); });
  let resolve!: (value: unknown) => void;
  get.mockReturnValueOnce(new Promise((done) => { resolve = done; }));
  let pending!: Promise<void>;
  act(() => { pending = hook.result.current.loadOlderMessages(); });
  act(() => hook.result.current.newChat());
  await act(async () => { resolve({ conversation, messages: [message(1)], nextCursor: null }); await pending; });
  expect(hook.result.current.messages).toEqual([]);
  expect(hook.result.current.conversationId).toBeNull();
  qc.clear();
});
