import { beforeEach, describe, expect, it } from "vitest";
import { eq } from "drizzle-orm";
import { db, resetDatabase } from "./helpers/db";
import { configTable, tasks, taskPlacements } from "../src/db/schema";
import { ProjectsService } from "../src/services/projects.service";
import { TaskPlacementsService } from "../src/services/task-placements.service";
import { TaskService } from "../src/services/task.service";
import { TaskViewsService } from "../src/services/task-views.service";
import { ProjectFactsService } from "../src/services/project-facts.service";
const a = { type: "manager" as const, accountId: "a", workspaceId: "default" };
const b = { ...a, accountId: "b" };
const containers = new ProjectsService();
const placements = new TaskPlacementsService();
const service = new TaskService();
beforeEach(async () => { await resetDatabase(); await db.insert(configTable).values([{ key: "tasks_phase1_enabled", value: "true" }, { key: "tasks_phase2_stage", value: "2c" }, { key: "tasks_phase3_enabled", value: "true" }]); });
describe("private project placement", () => {
  it("isolates two managers, workspaces and developer DTOs without task activity", async () => {
    const task = await service.create({ title: "Shared inbox", ownerType: null, ownerId: null }, a);
    const pa = await containers.write(a, { name: "A" }); const pb = await containers.write(b, { name: "B" });
    await placements.bulk(a, { preview: await placements.preview(a, { keys: [task.taskKey] }), placement: { projectId: pa.id, trackId: null } });
    await placements.bulk(b, { preview: await placements.preview(b, { keys: [task.taskKey] }), placement: { projectId: pb.id, trackId: null } });
    expect((await service.toDto(task, a) as any).placement.projectName).toBe("A");
    expect((await service.toDto(task, b) as any).placement.projectName).toBe("B");
    expect(await service.toDto(task, { ...a, type: "developer" })).not.toHaveProperty("placement");
    await expect(containers.requireProject({ ...a, workspaceId: "other" }, pa.id)).rejects.toMatchObject({ status: 404 });
    expect((await service.getById(task.id))!.updatedAt).toBe(task.updatedAt);
  });
  it("deduplicates descendants and rejects stale previews atomically and guarded undo", async () => {
    const parent = await service.create({ title: "Parent" }, a);
    const child = await service.create({ title: "Child", parentId: parent.id }, a);
    const hidden = await service.create({ title: "Private child", parentId: parent.id }, b);
    const project = await containers.write(a, { name: "Project" });
    const preview = await placements.preview(a, { keys: [parent.taskKey, child.taskKey], includeSubtasks: true });
    expect(preview.tasks.map((task) => task.taskKey)).not.toContain(hidden.taskKey);
    expect(preview.tasks).toHaveLength(2);
    const receipt = await placements.bulk(a, { preview, placement: { projectId: project.id, trackId: null } });
    await expect(placements.bulk(a, { preview, placement: null })).rejects.toMatchObject({ status: 409 });
    await containers.write(a, { archived: true }, project.id);
    await placements.bulk(a, receipt.undo);
    expect(await db.select().from(taskPlacements)).toHaveLength(0);
    await expect(placements.bulk(a, { preview: await placements.preview(a, { keys: [parent.taskKey] }), placement: { projectId: project.id, trackId: null } })).rejects.toMatchObject({ status: 409 });
  });
  it("filters lists and counts with distinct facts and Later resurfacing", async () => {
    const project = await containers.write(a, { name: "Facts" });
    const track = await containers.write(a, { name: "Track" }, undefined, project.id);
    const one = await service.create({ title: "Blocked", status: "blocked", scheduledOn: "2026-10-01", followUpAt: "2026-10-05T00:00:00Z" }, a);
    const parked = await service.create({ title: "Parked", later: true, hideUntil: "2026-10-06", scheduledOn: null, followUpAt: "2026-10-05T00:00:00Z" }, a);
    await placements.bulk(a, { preview: await placements.preview(a, { keys: [one.taskKey] }), placement: { projectId: project.id, trackId: track.id } });
    await placements.bulk(a, { preview: await placements.preview(a, { keys: [parked.taskKey] }), placement: { projectId: project.id, trackId: null } });
    const views = new TaskViewsService();
    expect(await views.count(a, { filters: { project: project.id } }, "2026-10-05")).toBe(2);
    expect(await views.run(a, { filters: { project: project.id, track: "none" } }, "2026-10-05")).toHaveLength(1);
    expect((await new ProjectFactsService().detail(a, project.id, "2026-10-05", "Asia/Kolkata")).facts).toMatchObject({ open: 2, blocked: 1, overdue: 1, followUpDue: 1 });
    expect((await new ProjectFactsService().detail(a, project.id, "2026-10-06")).facts.followUpDue).toBe(2);
    await db.update(tasks).set({ trackedByManagerId: "b", ownerId: "b" }).where(eq(tasks.id, one.id));
    expect(await views.run(a, { filters: { project: project.id } })).toHaveLength(1);
    expect((await service.toDto((await service.getById(one.id))!, a) as any).placement).toBeNull();
    expect(await db.select().from(taskPlacements)).toHaveLength(2);
  });
});
